export const CARGO_NOMBRES = {
  ASISTENTE_UATH: "ASISTENTE DE LA UATH",
  AUXILIAR_UATH: "TRABAJADORA SOCIAL INSTITUCIONAL",
  ANALISTA_TALENTO_HUMANO: "ANALISTA DE TALENTO HUMANO",
  RESPONSABLE_UATH: "RESPONSABLE DE LA UATH",
  ADMINISTRADOR_SISTEMA: "ADMINISTRADOR DEL SISTEMA",
};

export const CARGO_IDS = {
  ASISTENTE_UATH: "78de3b9c-a2f4-41ed-9823-bb72ee56d1f4",
  AUXILIAR_UATH: "5a7d49dd-926e-4eaa-8127-b05e9dae7e53",
  ANALISTA_TALENTO_HUMANO: "ae067d84-f43e-4c73-bab4-985f963331fa",
  RESPONSABLE_UATH: "718d8402-0f5e-4b58-af36-08564d8e496a",
  ADMINISTRADOR_SISTEMA: "c0c2cc49-4e23-43e8-aef8-835ae52ae7dc",
};

const CARGOS_ASISTENTE_UATH_EQUIVALENTES = [
  CARGO_IDS.ASISTENTE_UATH,
  CARGO_IDS.AUXILIAR_UATH,
  CARGO_IDS.ANALISTA_TALENTO_HUMANO,
];

const CARGOS_EQUIVALENTES = {
  [CARGO_IDS.ASISTENTE_UATH]: CARGOS_ASISTENTE_UATH_EQUIVALENTES,
  [CARGO_IDS.AUXILIAR_UATH]: CARGOS_ASISTENTE_UATH_EQUIVALENTES,
  [CARGO_IDS.ANALISTA_TALENTO_HUMANO]: CARGOS_ASISTENTE_UATH_EQUIVALENTES,
};

export function cargoIdsEquivalentes(cargoId) {
  return CARGOS_EQUIVALENTES[cargoId] || [cargoId];
}

export function cargoPuedeActuarComo(cargoActualId, cargoRequeridoId) {
  return cargoIdsEquivalentes(cargoRequeridoId).includes(cargoActualId);
}
